# Generated by Django 2.2.5 on 2019-09-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='datetimee',
            field=models.DateTimeField(null=True),
        ),
    ]
