# Generated by Django 2.2.5 on 2019-09-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_datetimee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='datetimee',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
