# Generated by Django 2.2.5 on 2019-09-09 21:32

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190909_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='json',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
