# Generated by Django 2.2.5 on 2019-09-10 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_event_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='json',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organiser', models.BooleanField(default=False)),
                ('org_name', models.CharField(blank=True, max_length=30)),
                ('org_description', models.TextField(blank=True)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateTimeField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
