# Generated by Django 2.2.5 on 2019-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20190910_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
