# Generated by Django 2.2.5 on 2019-09-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20190910_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
