# Generated by Django 2.2.5 on 2019-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_orgprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='followers',
            field=models.ManyToManyField(to='events.UserProfile'),
        ),
    ]
